version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: sqlserver2017
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=0988202071aA@
    ports:
      - "1433:1433"
    restart: always
